PUT http://localhost:53005/api/roles/5ba646d2-183e-4878-93fc-d9b60a362917
Content-Type: application/json

{
  "role_name": "PHP Dev",
  "permission": [
    "83c3fc6b-e22e-47af-9b2b-f5e4dee1719a"
  ],
  "content": "this is added so it's not null",
  "link": "linklinklink.com"
}