PUT http://localhost:53005/api/roles/9e383d63-e612-4cdd-a64d-a5e3db5c49ae
Content-Type: application/json

{
  "role_name": "Level 1 Support",
  "permission": [
    "83c3fc6b-e22e-47af-9b2b-f5e4dee1719a"
  ],
  "content": "Some random content that will be updated",
  "link": "example.link.com"
}