POST http://localhost:53005/api/roleLog/41685d72-75e2-493d-af64-8b46c077be95
Content-Type: application/json

{
  "invitation": 1,
  "initial_contact": 5,
  "replied": 3,
  "job_description": 4,
  "application_reviewed": 22,
  "proposed": 10,
  "accepted": 7,
  "rejected": 8,
  "follow_up": 12
}