POST http://localhost:53005/api/roleLog/0bbe2ca8-c167-47d3-8a1a-79f2b0cae57a
Content-Type: application/json

{
  "invitation": 1,
  "initial_contact": 5,
  "replied": 3,
  "job_description": 4,
  "application_reviewed": 22,
  "proposed": 10,
  "accepted": 7,
  "rejected": 8,
  "follow_up": 12
}