PUT http://localhost:53005/api/admin/users/36a6b127-b721-4802-98a3-4998349ac57e
Content-Type: application/json

{
  "email": "test@gmail.com",
  "name": "Testing",
  "admin": false,
  "disabled": true
}