PUT http://localhost:53005/api/admin/users/d560cd5f-4be3-4160-bbb4-5f1df9c99810
Content-Type: application/json

{
  "email": "test@gmail.com",
  "name": "Testoooooooo",
  "admin": false,
  "disabled": false
}